export default {
  activate_time: 1654931840,
  deactivate_time: 0,
  server_steam_id: '90160032596707328',
  lobby_id: '27764821520566381',
  league_id: 14270,
  lobby_type: 1,
  game_time: 1804,
  delay: 900,
  spectators: 1,
  game_mode: 2,
  average_mmr: 0,
  match_id: '6612026565',
  series_id: 675737,
  team_name_radiant: 'Nigma Galaxy SEA',
  team_name_dire: 'Polaris Esports',
  team_logo_radiant: '1869552972538783349',
  team_logo_dire: '1831290045925630948',
  team_id_radiant: 8572181,
  team_id_dire: 8525778,
  sort_score: 9001,
  last_update_time: 1654933632,
  radiant_lead: -9925,
  radiant_score: 11,
  dire_score: 15,
  players: [
    {
      account_id: 127077041,
      hero_id: 90,
      name: 'Xavius',
      country_code: 'gb',
      fantasy_role: 2,
      team_id: 8525778,
      team_name: 'Polaris Esports',
      team_tag: 'Polaris',
      is_locked: true,
      is_pro: true,
      locked_until: null,
    },
    {
      account_id: 355168766,
      hero_id: 4,
      name: 'Natsumi-',
      country_code: 'ph',
      fantasy_role: 1,
      team_id: 8525778,
      team_name: 'Polaris Esports',
      team_tag: 'Polaris',
      is_locked: true,
      is_pro: true,
      locked_until: null,
    },
    {
      account_id: 353479702,
      hero_id: 83,
      name: 'Tmv',
      country_code: 'ph',
      fantasy_role: 2,
      team_id: 8525778,
      team_name: 'Polaris Esports',
      team_tag: 'Polaris',
      is_locked: true,
      is_pro: true,
      locked_until: null,
    },
    {
      account_id: 113152484,
      hero_id: 129,
      name: 'Nevermine',
      country_code: 'la',
      fantasy_role: 1,
      team_id: 8525778,
      team_name: 'Polaris Esports',
      team_tag: 'Polaris',
      is_locked: true,
      is_pro: true,
      locked_until: null,
    },
    {
      account_id: 101460882,
      hero_id: 136,
      name: 'Boombui',
      country_code: 'th',
      fantasy_role: 2,
      team_id: 8572181,
      team_name: 'Nigma Galaxy SEA',
      team_tag: 'NGXSea',
      is_locked: true,
      is_pro: true,
      locked_until: null,
    },
    {
      account_id: 91369376,
      hero_id: 60,
      name: 'mizu',
      country_code: 'sg',
      fantasy_role: 1,
      team_id: 8572181,
      team_name: 'Nigma Galaxy SEA',
      team_tag: 'NGXSea',
      is_locked: true,
      is_pro: true,
      locked_until: null,
    },
    {
      account_id: 104512126,
      hero_id: 19,
      name: 'Lelouch-',
      country_code: 'ph',
      fantasy_role: 4,
      team_id: 8525778,
      team_name: 'Polaris Esports',
      team_tag: 'Polaris',
      is_locked: true,
      is_pro: true,
      locked_until: null,
    },
    {
      account_id: 152859296,
      hero_id: 26,
      name: 'Jhocam',
      country_code: 'id',
      fantasy_role: 2,
      team_id: 8572181,
      team_name: 'Nigma Galaxy SEA',
      team_tag: 'NGXSea',
      is_locked: true,
      is_pro: true,
      locked_until: null,
    },
    {
      account_id: 118233883,
      hero_id: 52,
      name: 'AlaCrity-',
      country_code: '',
      fantasy_role: 4,
      team_id: 8572181,
      team_name: 'Nigma Galaxy SEA',
      team_tag: 'NGXSea',
      is_locked: true,
      is_pro: true,
      locked_until: null,
    },
    {
      account_id: 181716137,
      hero_id: 15,
      name: 'inYourdreaM',
      country_code: 'id',
      fantasy_role: 1,
      team_id: 8572181,
      team_name: 'Nigma Galaxy SEA',
      team_tag: 'NGXSea',
      is_locked: true,
      is_pro: true,
      locked_until: null,
    },
  ],
  building_state: 4849874,
  weekend_tourney_tournament_id: 0,
  weekend_tourney_division: 0,
  weekend_tourney_skill_level: 0,
  weekend_tourney_bracket_round: 0,
  custom_game_difficulty: 0,
};
